//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoUpload.WinForm.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string LastPath {
            get {
                return ((string)(this["LastPath"]));
            }
            set {
                this["LastPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.101.12.30:32516/dp-oss/api/v1/file-storages/upload")]
        public string TargetURL {
            get {
                return ((string)(this["TargetURL"]));
            }
            set {
                this["TargetURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".dxf")]
        public string AllowedExtensions {
            get {
                return ((string)(this["AllowedExtensions"]));
            }
            set {
                this["AllowedExtensions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^([a-zA-Z0-9]+)\\s([a-zA-Z0-9]+)(?:\\s([0-9]+))?\\.(dxf)")]
        public string AllowedFileNameRules {
            get {
                return ((string)(this["AllowedFileNameRules"]));
            }
            set {
                this["AllowedFileNameRules"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1627160160700962818")]
        public string XTenantId {
            get {
                return ((string)(this["XTenantId"]));
            }
            set {
                this["XTenantId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12345678")]
        public string XTraceId {
            get {
                return ((string)(this["XTraceId"]));
            }
            set {
                this["XTraceId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1860922302836342786")]
        public string XUserId {
            get {
                return ((string)(this["XUserId"]));
            }
            set {
                this["XUserId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mabin")]
        public string XUserName {
            get {
                return ((string)(this["XUserName"]));
            }
            set {
                this["XUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.101.12.30:32516/dp-mould/api/v1/mould-sizes/cutter")]
        public string WriteURL {
            get {
                return ((string)(this["WriteURL"]));
            }
            set {
                this["WriteURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.101.12.30:32516/dp-product/open/api/v1/parts/attr-value")]
        public string QueryURL {
            get {
                return ((string)(this["QueryURL"]));
            }
            set {
                this["QueryURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.101.12.30:32516/dp-mould/api/v1/mould-sizes/list")]
        public string ListURL {
            get {
                return ((string)(this["ListURL"]));
            }
            set {
                this["ListURL"] = value;
            }
        }
    }
}
